version: "3"
services:
  py3:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/work
    expose:
      - "8888"
    ports:
      - "8888:8888"
    volumes:
      - ./root_jupyter:/root/.jupyter
      - ./work:/work